apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/micheal-ndoh/auth-kubernetees-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SALT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SALT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_EXPIRATION 